input:
  label: kafka_input
  kafka:
    addresses:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
    topics:
      - "${DEVICE_STATUS_TOPIC:topic.device.status}"
    consumer_group: "zone.dimo.export.elastic"
    client_id: ${CONTAINER_NAME:localhost}-stream-vss-status
    rack_id: ${NODE_NAME:localhost}
    commit_period: 1s
    fetch_buffer_cap: 500
    checkpoint_limit: 500
pipeline:
  threads: -1
  processors:
    - label: remove_vin
      bloblang: |
        root = this
        root.data.vin = deleted()
    - vss_vehicle:
    - sql_insert:
        driver: clickhouse
        dsn: clickhouse://${CLICKHOUSE_HOST:localhost}:${CLICKHOUSE_TCP_PORT:9000}?username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}&dial_timeout=200ms&max_execution_time=60
        table: vehicle
        columns: []
        args_mapping: root = this
    - catch:
        - log:
            message: "Processing failed due to: ${!error()}"
output:
  stdout:
    codec: lines
logger:
  level: ALL
  format: logfmt
  add_timestamp: true
