input:
  file:
    paths: [./testfile.json]
    codec: all-bytes

buffer:
  none: {}
pipeline:
  threads: -1
  processors:
    - mapping: |
        root = this.format_json()
    - unarchive:
        format: json_array
    - vss_vehicle:
    - sql_insert:
        driver: clickhouse
        dsn: clickhouse://localhost:9000?username=admin&password=password&dial_timeout=200ms&max_execution_time=60
        table: vehicle2
        columns: []
        args_mapping: root = this
    - catch:
        - log:
            message: "Processing failed due to: ${!error()}"
output:
  stdout:
    codec: lines
logger:
  level: ALL
  format: logfmt
  add_timestamp: true
