input:
  label: kafka_input
  kafka:
    addresses:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
    topics:
      - '${DEVICE_STATUS_TOPIC:topic.device.status.private}'
    consumer_group: "zone.dimo.export.clickhouse"
    client_id: ${CONTAINER_NAME:localhost}-benthos-plugin-status
    rack_id: ${NODE_NAME:localhost}
    commit_period: 1s
    fetch_buffer_cap: 500
    checkpoint_limit: 500

pipeline:
  processors:
    - label: remove_vin
      bloblang: |
        root = this
        root.data.vin = deleted()
    - dimo_vss:
    - catch:
        - log:
            message: "Processing failed due to: ${!error()}"

output:
  fallback:
  - sql_insert:
        driver: clickhouse
        dsn: clickhouse://${CLICKHOUSE_HOST:localhost}:${CLICKHOUSE_TCP_PORT:9000}?username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}&dial_timeout=200ms&max_execution_time=60
        table: dimo
        columns: []
        args_mapping: root = this
  - drop: {}