apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benthos-plugin.fullname" . }}
  labels:
    {{- include "benthos-plugin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "benthos-plugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/configenv.yaml" ) . | sha256sum }}
        checksum/stream: {{ include (print $.Template.BasePath "/configmap.yaml" ) . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "benthos-plugin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "benthos-plugin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/benthos-plugin"]
          args:  ["-w" "-c" "/config/config.yaml" "streams" "/streams/"]
          envFrom:
          - configMapRef:
              name: {{ include "benthos-plugin.fullname" . }}-config
          - secretRef:
              name: {{ include "benthos-plugin.fullname" . }}-secret
          env:
          - name: CONTAINER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CONTAINER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
{{ toYaml .Values.ports | indent 12 }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: status
              mountPath: /streams/devicestatus.yaml
              subPath: devicestatus.yaml
            - name: events
              mountPath: /streams/deviceevents.yaml
              subPath: deviceevents.yaml
            - name: dbc
              mountPath: /streams/dbcdecoding.yaml
              subPath: dbcdecoding.yaml                    
            - name: config
              mountPath: /config
      volumes:
        - name: status
          configMap:
            name: {{ include "benthos-plugin.fullname" . }}-stream-config
            items:
              - key: devicestatus.yaml
                path: devicestatus.yaml
        - name: events
          configMap:
            name: {{ include "benthos-plugin.fullname" . }}-stream-config
            items:
              - key: deviceevents.yaml
                path: deviceevents.yaml     
        - name: config
          configMap:
            name: {{ include "benthos-plugin.fullname" . }}-stream-config
            items:
              - key: config.yaml
                path: config.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
